### ISSUE TITLE
Dynamically get system colour values

### ISSUE THREAD

**Issue by roke-julian-lockhart** [mikepan/BlenderThemes#1]
For the sake of future-proofing and consistency (especially for those who modify macOS somewhat) is there a way for the theme to get the system colour values? This is a pretty common thing to do on Windows, but I wouldn't know where to start on macOS nor whether Blender would support this any significant capacity.

**Comment by MikePanSAI** [comment]
I like that idea, but that's up for Blender to implement, not the theme (which is what this is).

**Comment by roke-julian-lockhart** [comment]
You can't include code with a Blender theme?
